### ISSUE TITLE
demo中mobilenet_v2 模型转换后应用到Android端编译出错

### ISSUE THREAD

**Issue by njhhg** [XiaoMi/mace#188] opened 2018-09-06 11:26 UTC
Before you open an issue, please make sure you have tried the following steps:

Make sure your environment is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
Have you ever read the document for your usage?
The form below must be filled.
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
NDK version(e.g., 15c): r12b
GCC version(if compiling for host, e.g., 5.4.0): 5.4.0
MACE version (Use the command: git describe --long --tags): v0.9.0-67-g0a14e02
Python version(3.5): 3.5
Bazel version (e.g., 0.13.0):0.13.0
Model deploy file (*.yml)
```

library_name: mobilenet-v2
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

Describe the problem

`
根据mace官方文档步骤，将编译mace通用库、模型转换已经成功（官方mace 镜像），但最终应用到Android上时，项目无法正常编译通过`

Steps to reproduce the problem:

1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
Error information / logs

Please include the full log and/or traceback here.

  ```
 `ce` to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x498): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x4b0): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x4c4): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x4dc): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o):mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x52c): more undefined references to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)' follow
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o): In function `mace::mobilenet_v2::CreateOperator178(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x600): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x690): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x868): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x888): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x8a8): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o):mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0x8c8): more undefined references to `std::string::_Rep::_M_destroy(std::allocator<char> const&)' follow
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o): In function `mace::mobilenet_v2::CreateOperator178(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0xd3c): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0xd40): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator178EPNS_11OperatorDefE+0xd84): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o): In function `mace::mobilenet_v2::CreateOperator179(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x48): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x64): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x80): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x84): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x484): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x498): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x4b0): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x4c4): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x4dc): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o):mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x52c): more undefined references to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)' follow
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o): In function `mace::mobilenet_v2::CreateOperator179(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x604): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x694): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x86c): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x88c): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x8ac): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o):mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0x8cc): more undefined references to `std::string::_Rep::_M_destroy(std::allocator<char> const&)' follow
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o): In function `mace::mobilenet_v2::CreateOperator179(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0xd40): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0xd44): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op17.cc:(.text._ZN4mace12mobilenet_v217CreateOperator179EPNS_11OperatorDefE+0xd88): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o):(.text.startup+0x18): undefined reference to `std::ios_base::Init::Init()'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o):(.text.startup+0x1c): undefined reference to `std::ios_base::Init::~Init()'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op17.o):(.text.startup+0x20): undefined reference to `std::ios_base::Init::~Init()'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o): In function `mace::mobilenet_v2::CreateOperator180(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x48): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x64): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x80): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x84): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x3f8): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x40c): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x424): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x438): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x450): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x4a0): more undefined references to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)' follow
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o): In function `mace::mobilenet_v2::CreateOperator180(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x574): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x604): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x7dc): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x7fc): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x81c): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0x83c): more undefined references to `std::string::_Rep::_M_destroy(std::allocator<char> const&)' follow
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o): In function `mace::mobilenet_v2::CreateOperator180(mace::OperatorDef*)':
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0xcb0): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0xcb4): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
mace/codegen/models/mobilenet_v2/op18.cc:(.text._ZN4mace12mobilenet_v217CreateOperator180EPNS_11OperatorDefE+0xcf8): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x68): undefined reference to `std::string::assign(std::string const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x98): undefined reference to `std::string::assign(std::string const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0xdc): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0xe4): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x124): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x134): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x144): undefined reference to `std::string::assign(std::string const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x188): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x190): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x1d0): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x1e0): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x1f0): undefined reference to `std::string::assign(std::string const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o):(.text._ZN4mace12_GLOBAL__N_18UpdateOpEPNS_11OperatorDefERKSsS4_RKSt6vectorISsSaISsEES9_RKS5_INS_8DataTypeESaISA_EEjRKS5_IiSaIiEE+0x378): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op18.o): In function `mace::mobilenet_v2::CreateOperator181(mace::OperatorDef*)':

```
  STDOUT:

  STDERR:

**Comment by lee-bin** [comment] 2018-09-06 11:53
请按[ISSUE TEMPLATE](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)填写，以利于有效定位问题，不要遗漏任何一项，谢谢。

**Comment by njhhg** [comment] 2018-09-07 01:19
@lee-bin 已完善

**Comment by lee-bin** [comment] 2018-09-07 01:41
First, read carefully about https://mace.readthedocs.io/en/latest/installation/env_requirement.html.
So, you can use python 2.7 and NDK r15c.

**Comment by jliu22** [comment] 2018-09-10 18:46
I successfully built the demo with mobilenet on ubuntu 16.04 with python 2.7 and NDK r15c.
$ python tools/converter.py convert --config=~/mace-models/mobilenet-v1/mobilenet-v1.yml

I met below issue then fixed by downgrade tensor flow to 1.5.0
$ pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com tensorflow==1.5.0

Transform model to one that can better run on device
Traceback (most recent call last):
  File "tools/converter.py", line 1757, in <module>
    flags.func(flags)
  File "tools/converter.py", line 844, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 769, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/work/.dev/mace/tools/sh_commands.py", line 592, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.SignalException_SIGILL: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=builds/downloads/f330dec17e45a8626cfb225ddce95051.pb --weight_file= --model_checksum=71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6 --weight_checksum= --input_node=input --output_node=MobilenetV1/Predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

**Comment by lee-bin** [comment] 2018-09-11 01:54
@jliu22 
What's your question since you have built the demo successfully?
How did you come across the issue above?
I don't see any relation between your issue and this issue, so maybe you can open a new issue and clarify it.

**Comment by jliu22** [comment] 2018-09-11 21:11
I will try to reproduce and open a new issue.
Thanks!

**Closed** 2018-09-18 03:28 UTC
