### ISSUE TITLE
模型转换工具支持linux os吗？

### ISSUE THREAD

**Issue by tinalazy** [XiaoMi/mace#235] opened 2018-11-01 09:10 UTC
### System information
- OS Platform and Distribution ( Linux Ubuntu 16.04)
- NDK version(15c)
- GCC version( 5.4.0)
- MACE version (  newest)
- Python version(2.7)**: 
- Bazel version ( 0.13.1)

你好我只是想简单的测试一下 mace在linux 下跑我们的模型大概是什么速度。
 
有咩有demo可以直接修改两下在linux 上跑的。模型转换工具我也一直使用失败提示

Traceback (most recent call last):
  File "/home/anjing/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/anjing/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 132, in main
    from mace.python.tools.converter_tool import tensorflow_converter
  File "/home/anjing/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 18, in <module>
    import tensorflow as tf
  File "/home/anjing/yes/lib/python2.7/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/anjing/yes/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/anjing/yes/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 15, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/home/anjing/yes/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 15, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/anjing/yes/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 15, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/anjing/yes/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 15, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/anjing/yes/lib/python2.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/anjing/deeplearning/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/home/anjing/yes/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1

**Comment by tinalazy** [comment] 2018-11-01 09:40
> 转换工具支持linux pc，跑具体模型请参考文档。
> 
> 在.yml文件中设置target_abis为host。
> 
> https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#deployment-file

感谢您的回复。我想我没说清楚，就是本地是linux intel平台 ，但是跑的目标板是3399平台

**Comment by TonyMou** [comment] 2018-11-01 10:04
Duplicate of #36

**Comment by nolanliou** [comment] 2018-11-02 02:40
貌似是tensorflow安装有问题吧

**Closed** 2018-12-18 11:38 UTC
