### ISSUE TITLE
ERROR: in target '//external:android/crosstool': no such package '@androidndk//': Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME  environment variable must be set.

### ISSUE THREAD

**Issue by cx1628555321** [XiaoMi/mace#191] opened 2018-09-12 02:10 UTC
Before you open an issue, please make sure you have tried the following steps:

1. I am sure that my **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. I have  read the document for my usage.

------------------------

### System information
-  Linux Ubuntu 14.04 LTS  (VMware Wokerstation)
- ANDROID NDK version : android-ndk-r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version: 2.7.6 
- **Bazel version: 0.16.1

### Model deploy file (*.yml)
```I want convert mobilnenet-v2 from model zoo，the yaml：
library_name: mobilenet-v2
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

### Describe the problem
I have compiled the mace source code in the same environment and have successfully converted the 
style conversion model and one of my model into a file. Now I want to convert mobilnenet-v2 into code
 and I get an error:

******************************************
          Building model library          
******************************************

* Build //mace/codegen:generated_models with ABI armeabi-v7a
ERROR: in target '//external:android/crosstool': no such package '@androidndk//': Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME  environment variable must be set.
INFO: Elapsed time: 0.517s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
Traceback (most recent call last):
  File "tools/converter.py", line 1757, in <module>
    flags.func(flags)
  File "tools/converter.py", line 847, in convert_func
    build_model_lib(configs, flags.address_sanitizer)
  File "tools/converter.py", line 816, in build_model_lib
    symbol_hidden=True
  File "/home/chenxiang/Mi_Mace/mace-master/tools/sh_commands.py", line 318, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
....
I will also encounter this problem when recompiling the maces source.I checked the environment 
variables and everything seems to be fine.
such as this:

chenxiang@ubuntu:~/Mi_Mace/mace-master$ echo $ANDROID_NDK_HOME
/home/chenxiang/Android/ndk/android-ndk-r15c
chenxiang@ubuntu:~/Mi_Mace/mace-master$ 

What can I do to solve the problem?

**Comment by cx1628555321** [comment] 2018-09-12 03:55
Hi 
When I build Mace mace source code again,
 I encountered the same problem again.I execute that command to verify. the ANDROID_NDK_HOME is right.
.............

**Comment by yejw5** [comment] 2018-09-13 08:00
The problem is caused by running with sudo permission, where env variables are different with current user. Close this issue, feel free to reopen it if any question still not resolved.

**Closed by yejw5** 2018-09-13 08:00 UTC

**Comment by yuhaocan** [comment] 2018-12-17 05:04
I also encountered the same problem.
```
build shared lib for armeabi-v7a + cpu_gpu_dsp
WARNING: The following configs were expanded more than once: [cross_compile]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: in target '//external:android/crosstool': no such package '@androidndk//': Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME  environment variable must be set.
INFO: Elapsed time: 0.209s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
I had configure NDK ENV

**Comment by Ijustakid** [comment] 2020-06-15 09:04
'su root' will solve it.

**Comment by ystsaan** [comment] 2021-05-13 09:18
@yejw5 cmake users can manually modify the "-DCMAKE_TOOLCHAIN_FILE"  in tools/cmake/cmake-build-armeabi-v7a.sh to specify android ndk being used manually. So how can i modify tools/bazel_build_standalone_lib.sh to specify android ndk directory being used? I searched the "android" keyword in bazel_build_standalone_lib.sh but the result seems not related to android ndk directory used.
